target:   sample    # 対象のtexファイルの名前
bbl_cmd:  bibtex    # .bblを生成するコマンド
bb_cmd:   ebb       # .bbを生成するコマンド
tex_cmd:  platex    # .texをコンパイルするコマンド
dvi_cmd:  dvipdfmx  # .dviをpdfにするコマンド
open_cmd: open      # できたpdfを開くコマンド
